### ISSUE TITLE
Clone sometimes doesn't add k8s.io/CloneOf annotation to target PVC

### ISSUE THREAD

**Issue by awels** [kubevirt/containerized-data-importer#560]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Sometimes when cloning a PVC the cloneOf annotation does not get added to the target PVC. I believe the following sequence of events happens:
1. target PVC is created
2. Controller sees new PVC, and creates source/target pods. And puts Running annotation on target PVC.
3. The clone completes. And the target pod is cleaned up before the clone controller is allowed to run. The clone controller doesn't see the completed pod, and thus never updates the annotation on the target PVC.

**What you expected to happen**:
The cleanup of the finished pod will trigger the annotation to be put on the target PVC.

**How to reproduce it (as minimally and precisely as possible)**:
Since this is a race condition (does the pod get cleaned before the clone controller gets a chance to run, its hard to reproduce). The CI does fail on it sometimes. I will attach a failed run log to this bug.
**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
master
- Kubernetes version (use `kubectl version`):
all supported versions have the issue.
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
```
I1206 13:57:52.084692       1 datavolume-controller.go:571] Processing object: create-image
I1206 13:58:04.799242       1 datavolume-controller.go:571] Processing object: source-pvc
I1206 13:58:04.804338       1 upload-controller.go:332] Successfully synced 'cdi-e2e-tests-cloner-27m82/source-pvc'
I1206 13:58:04.805122       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/source-pvc"
I1206 13:58:04.805137       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/source-pvc"
I1206 13:58:04.805144       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/source-pvc" completed
I1206 13:58:04.805155       1 util.go:61] pvc annotation "k8s.io/CloneRequest" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/source-pvc"
I1206 13:58:04.805160       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/source-pvc" completed
I1206 13:58:05.054462       1 datavolume-controller.go:571] Processing object: source-pvc
I1206 13:58:05.059568       1 upload-controller.go:332] Successfully synced 'cdi-e2e-tests-cloner-27m82/source-pvc'
I1206 13:58:05.059591       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/source-pvc"
I1206 13:58:05.059596       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/source-pvc"
I1206 13:58:05.059603       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/source-pvc" completed
I1206 13:58:05.059612       1 util.go:61] pvc annotation "k8s.io/CloneRequest" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/source-pvc"
I1206 13:58:05.059616       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/source-pvc" completed
I1206 13:58:05.064803       1 datavolume-controller.go:571] Processing object: source-pvc
I1206 13:58:05.070065       1 upload-controller.go:332] Successfully synced 'cdi-e2e-tests-cloner-27m82/source-pvc'
I1206 13:58:05.070094       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/source-pvc"
I1206 13:58:05.070103       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/source-pvc"
I1206 13:58:05.070112       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/source-pvc" completed
I1206 13:58:05.070125       1 util.go:61] pvc annotation "k8s.io/CloneRequest" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/source-pvc"
I1206 13:58:05.070133       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/source-pvc" completed
I1206 13:58:09.037089       1 datavolume-controller.go:571] Processing object: target-pvc
I1206 13:58:09.042252       1 clone-controller.go:236] PVC phase for PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is Pending
I1206 13:58:09.042276       1 clone-controller.go:239] storageClassName used by PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is "local"
I1206 13:58:09.042579       1 upload-controller.go:332] Successfully synced 'cdi-e2e-tests-cloner-27m82/target-pvc'
I1206 13:58:09.042590       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.042595       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.042600       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.047375       1 clone-controller.go:260] ProcessNextPvcItem: next pvc to process: "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.047437       1 expectations.go:170] Controller cdi-e2e-tests-cloner-27m82/target-pvc either never recorded expectations, or the ttl expired.
I1206 13:58:09.047443       1 expectations.go:187] Setting expectations &expectations.ControlleeExpectations{add:0, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:09.047459       1 expectations.go:215] Raised expectations &expectations.ControlleeExpectations{add:1, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:09.056039       1 upload-controller.go:273] Processing object: clone-source-pod-r6hf7
I1206 13:58:09.056141       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:09.056184       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:09.056514       1 util.go:419] cloning source pod "cdi-e2e-tests-cloner-27m82/clone-source-pod-r6hf7" (image: "registry:5000/cdi-cloner:latest") created
I1206 13:58:09.056533       1 expectations.go:215] Raised expectations &expectations.ControlleeExpectations{add:1, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:09.056191       1 expectations.go:206] Lowered expectations &expectations.ControlleeExpectations{add:1, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:09.060675       1 upload-controller.go:273] Processing object: clone-source-pod-r6hf7
I1206 13:58:09.060702       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:09.060728       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:09.061334       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.061347       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.061354       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.070961       1 upload-controller.go:273] Processing object: clone-target-pod-lr75g
I1206 13:58:09.071005       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:09.071042       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:09.071053       1 expectations.go:206] Lowered expectations &expectations.ControlleeExpectations{add:0, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:09.075285       1 util.go:517] cloning target pod "cdi-e2e-tests-cloner-27m82/clone-target-pod-lr75g" (image: "registry:5000/cdi-cloner:latest") created
I1206 13:58:09.075312       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.075324       1 clone-controller.go:236] PVC phase for PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is Pending
I1206 13:58:09.075330       1 clone-controller.go:239] storageClassName used by PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is "local"
I1206 13:58:09.076142       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.076155       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.076162       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.077806       1 upload-controller.go:273] Processing object: clone-source-pod-r6hf7
I1206 13:58:09.077829       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:09.077859       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:09.079704       1 clone-controller.go:260] ProcessNextPvcItem: next pvc to process: "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.079752       1 expectations.go:152] Controller expectations fulfilled &expectations.ControlleeExpectations{add:0, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:09.079772       1 util.go:161] updatePVC: updating pvc "cdi-e2e-tests-cloner-27m82/target-pvc" with anno: map[cdi.kubevirt.io/storage.pod.phase:Pending] and label: map[app:containerized-data-importer]
I1206 13:58:09.082999       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.083014       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.083022       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.085092       1 util.go:198] updatePVC: pvc "cdi-e2e-tests-cloner-27m82/target-pvc" updated
I1206 13:58:09.085115       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.085129       1 clone-controller.go:236] PVC phase for PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is Pending
I1206 13:58:09.085137       1 clone-controller.go:239] storageClassName used by PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is "local"
I1206 13:58:09.085412       1 datavolume-controller.go:571] Processing object: target-pvc
I1206 13:58:09.090577       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.090586       1 upload-controller.go:332] Successfully synced 'cdi-e2e-tests-cloner-27m82/target-pvc'
I1206 13:58:09.090598       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.090608       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.091704       1 clone-controller.go:260] ProcessNextPvcItem: next pvc to process: "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.091770       1 expectations.go:152] Controller expectations fulfilled &expectations.ControlleeExpectations{add:0, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:09.091792       1 util.go:161] updatePVC: updating pvc "cdi-e2e-tests-cloner-27m82/target-pvc" with anno: map[cdi.kubevirt.io/storage.pod.phase:Pending] and label: map[app:containerized-data-importer]
I1206 13:58:09.092319       1 upload-controller.go:273] Processing object: clone-target-pod-lr75g
I1206 13:58:09.092334       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:09.092363       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:09.097498       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.097517       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.097524       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.098395       1 util.go:185] pvc "cdi-e2e-tests-cloner-27m82/target-pvc" is stale, re-trying
I1206 13:58:09.122922       1 datavolume-controller.go:571] Processing object: target-pvc
I1206 13:58:09.128316       1 upload-controller.go:332] Successfully synced 'cdi-e2e-tests-cloner-27m82/target-pvc'
I1206 13:58:09.131890       1 upload-controller.go:273] Processing object: clone-target-pod-lr75g
I1206 13:58:09.131915       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:09.131943       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.131953       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.131968       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.131980       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:09.134309       1 datavolume-controller.go:571] Processing object: target-pvc
I1206 13:58:09.140341       1 upload-controller.go:332] Successfully synced 'cdi-e2e-tests-cloner-27m82/target-pvc'
I1206 13:58:09.140383       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.140391       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.140398       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:09.143166       1 upload-controller.go:273] Processing object: clone-target-pod-lr75g
I1206 13:58:09.143191       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:09.143326       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:09.150082       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.150107       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:09.150118       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:10.106454       1 util.go:185] pvc "cdi-e2e-tests-cloner-27m82/target-pvc" is stale, re-trying
I1206 13:58:11.106545       1 util.go:198] updatePVC: pvc "cdi-e2e-tests-cloner-27m82/target-pvc" updated
I1206 13:58:11.106566       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:11.106579       1 clone-controller.go:236] PVC phase for PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is Bound
I1206 13:58:11.106585       1 clone-controller.go:239] storageClassName used by PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is "local"
I1206 13:58:11.109080       1 clone-controller.go:260] ProcessNextPvcItem: next pvc to process: "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:11.109137       1 expectations.go:152] Controller expectations fulfilled &expectations.ControlleeExpectations{add:0, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:11.109154       1 util.go:161] updatePVC: updating pvc "cdi-e2e-tests-cloner-27m82/target-pvc" with anno: map[cdi.kubevirt.io/storage.pod.phase:Pending] and label: map[]
I1206 13:58:11.113565       1 util.go:198] updatePVC: pvc "cdi-e2e-tests-cloner-27m82/target-pvc" updated
I1206 13:58:11.113587       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:12.130581       1 upload-controller.go:273] Processing object: clone-target-pod-lr75g
I1206 13:58:12.131521       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:12.131554       1 controller.go:121] Processing object: clone-target-pod-lr75g
I1206 13:58:12.136693       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:12.136718       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:12.136737       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:12.136693       1 clone-controller.go:236] PVC phase for PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is Bound
I1206 13:58:12.136748       1 clone-controller.go:239] storageClassName used by PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is "local"
I1206 13:58:12.137422       1 upload-controller.go:273] Processing object: clone-source-pod-r6hf7
I1206 13:58:12.137438       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:12.137455       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:12.139122       1 clone-controller.go:260] ProcessNextPvcItem: next pvc to process: "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:12.139170       1 expectations.go:152] Controller expectations fulfilled &expectations.ControlleeExpectations{add:0, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:12.139186       1 util.go:161] updatePVC: updating pvc "cdi-e2e-tests-cloner-27m82/target-pvc" with anno: map[cdi.kubevirt.io/storage.pod.phase:Running] and label: map[]
I1206 13:58:12.142583       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:12.142600       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:12.142607       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:12.160953       1 util.go:198] updatePVC: pvc "cdi-e2e-tests-cloner-27m82/target-pvc" updated
I1206 13:58:12.160973       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:12.160985       1 clone-controller.go:236] PVC phase for PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is Bound
I1206 13:58:12.160991       1 clone-controller.go:239] storageClassName used by PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is "local"
I1206 13:58:12.163362       1 datavolume-controller.go:571] Processing object: target-pvc
I1206 13:58:12.168605       1 clone-controller.go:260] ProcessNextPvcItem: next pvc to process: "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:12.168686       1 expectations.go:152] Controller expectations fulfilled &expectations.ControlleeExpectations{add:0, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:12.168711       1 util.go:161] updatePVC: updating pvc "cdi-e2e-tests-cloner-27m82/target-pvc" with anno: map[cdi.kubevirt.io/storage.pod.phase:Running] and label: map[]
I1206 13:58:12.168988       1 upload-controller.go:332] Successfully synced 'cdi-e2e-tests-cloner-27m82/target-pvc'
I1206 13:58:12.169105       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:12.169115       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:12.169121       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:12.180367       1 util.go:185] pvc "cdi-e2e-tests-cloner-27m82/target-pvc" is stale, re-trying
I1206 13:58:13.191867       1 util.go:198] updatePVC: pvc "cdi-e2e-tests-cloner-27m82/target-pvc" updated
I1206 13:58:13.191914       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:13.191942       1 clone-controller.go:236] PVC phase for PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is Bound
I1206 13:58:13.191958       1 clone-controller.go:239] storageClassName used by PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is "local"
I1206 13:58:13.200360       1 clone-controller.go:260] ProcessNextPvcItem: next pvc to process: "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:13.200486       1 expectations.go:152] Controller expectations fulfilled &expectations.ControlleeExpectations{add:0, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:13.200536       1 util.go:161] updatePVC: updating pvc "cdi-e2e-tests-cloner-27m82/target-pvc" with anno: map[cdi.kubevirt.io/storage.pod.phase:Running] and label: map[]
I1206 13:58:13.207705       1 util.go:198] updatePVC: pvc "cdi-e2e-tests-cloner-27m82/target-pvc" updated
I1206 13:58:13.207751       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:15.143802       1 upload-controller.go:273] Processing object: clone-source-pod-r6hf7
I1206 13:58:15.143827       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:15.143853       1 controller.go:121] Processing object: clone-source-pod-r6hf7
I1206 13:58:15.152286       1 clone-controller.go:236] PVC phase for PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is Bound
I1206 13:58:15.152308       1 clone-controller.go:239] storageClassName used by PVC "cdi-e2e-tests-cloner-27m82/target-pvc" is "local"
I1206 13:58:15.152505       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.endpoint" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:15.152516       1 util.go:61] pvc annotation "cdi.kubevirt.io/storage.import.source" not found, skipping pvc "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:15.152525       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed
I1206 13:58:15.157530       1 clone-controller.go:260] ProcessNextPvcItem: next pvc to process: "cdi-e2e-tests-cloner-27m82/target-pvc"
I1206 13:58:15.157598       1 expectations.go:152] Controller expectations fulfilled &expectations.ControlleeExpectations{add:0, del:0, key:"cdi-e2e-tests-cloner-27m82/target-pvc", timestamp:time.Time{wall:0xbefa689c42d3e6e5, ext:788314632431, loc:(*time.Location)(0x1acb1c0)}}
I1206 13:58:15.157620       1 util.go:161] updatePVC: updating pvc "cdi-e2e-tests-cloner-27m82/target-pvc" with anno: map[cdi.kubevirt.io/storage.pod.phase:Running] and label: map[]
I1206 13:58:15.162621       1 util.go:198] updatePVC: pvc "cdi-e2e-tests-cloner-27m82/target-pvc" updated
I1206 13:58:15.162642       1 controller.go:202] ProcessNextPvcItem: processing pvc "cdi-e2e-tests-cloner-27m82/target-pvc" completed

INFO: Pod log
cloner: Starting clone target
cloner: check if the fifo pipe was created by the cloning source pod
cloner: 0: fifo pipe has not been created by the source pod. Waiting 3 seconds before checking again...
cloner: check if the fifo pipe was created by the cloning source pod
/tmp/clone/image /
cloner: extract the image from /tmp/clone/socket/f65dd91d-f95e-11e8-8e85-525500d15501/pipe into /tmp/clone/image directory
I1206 13:58:14.306058       7 clonertarget.go:51] Starting cloner target
I1206 13:58:14.583331       7 clonertarget.go:100] Reading total size
I1206 13:58:14.587072       7 clonertarget.go:140] total size: 85

STEP: Destroying namespace "cdi-e2e-tests-cloner-27m82" for this suite.
STEP: [AfterEach] Clean up target PVC

• Failure [88.616 seconds]
Cloner Test Suite
/home/awels/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:30
  A valid source and target given
  /home/awels/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:47
    Should clone data within same name space [It]
    /home/awels/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:48

    Unexpected error:
        <*errors.errorString | 0xc4200c54c0>: {                                                                                                                                                                   
            s: "timed out waiting for the condition",                                                                                                                                                             
        }                                                                                                                                                                                                         
        timed out waiting for the condition                                                                                                                                                                       
    occurred                                                                                                                                                                                                      

    /home/awels/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:107
------------------------------
```

**Comment by zvikorn** [comment]
Fixed by https://github.com/kubevirt/containerized-data-importer/pull/573

**Comment by zvikorn** [comment]
The pods were delete before the controller had a chance to update the PVC with the 'CloneOf' annotation since the 'defer' call to delete the pods, was called inside the 'if' clause, which caused the deletion of the pods at the end of the 'if' clause. Note: before the fix - even if we do not know exactly when the delete call will be executed, it can be executed immediately after the 'if' clause.

**Comment by awels** [comment]
Looks like there is still a race [here](https://jenkins.ovirt.org/job/kubevirt_containerized-data-importer_standard-check-pr/990//artifact/check-patch.k8s-1.11.0-release.el7.x86_64/mock_logs/script/stdout_stderr.log) The log shows the pods completed successfully, but the annotation never appears.

**Comment by awels** [comment]
This is still an issue, the functional tests are failing randomly on this.
